---

# Dist directories
########################################################################################################################
tpl_directories:
  - path: "../dist/{{ level }}-{{ os_version }}/configs/"
